import re

def verify_citation(answer_sentence, corpus_sections):
    """
    Verifies that all citations in the answer sentence (in format [id]) are present in the retrieved corpus sections.
    
    Args:
        answer_sentence (str): The sentence generated by the model.
        corpus_sections (list): A list of available corpus section IDs.
        
    Returns:
        bool: True if all citations are valid, False otherwise.
    """
    # Find all citations in the format [id]
    citations = re.findall(r'\[(.*?)\]', answer_sentence)
    
    for citation in citations:
        if citation not in corpus_sections:
            return False
    return True
