#!/usr/bin/env python3
"""Lane scope gate for agent changes: each lane may only touch its own files.

    git diff --name-only origin/main...HEAD | python3 scripts/hive_gate.py --branch agent/hermes/T-001

Exit 0 when every changed path is inside the lane's scope, 1 otherwise. Non-agent branches pass.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PREFIX = Path(__file__).resolve().parents[1].name  # awesome-indian-exams
# Regenerated by the JEVX lane only, so parallel worker changes never conflict on them.
GENERATED = ("README.md", "UPDATES.md", "resources/all-exams.md", "resources/overlap-map.md")
# The gate, the hive machinery and agent configuration: OpenCode's job, never Hermes'.
TOOLING = ("scripts/", "tests/", "ops/", ".agents/", "opencode.json")
# The hive's own guardrails. No agent lane may change them, so agents can never loosen the rules they are held
# to. Only the owner changes these, through a normal reviewed pull request.
PROTECTED = ("scripts/hive_gate.py", "scripts/evidence_gate.py", "ops/judge.py", "ops/run-hourly.sh",
             "ops/merge_ready.sh", "ops/agentctl.py", "ops/free_agent.py", "ops/official-domains.txt",
             "ops/hive.toml", "ops/prompts/", ".agents/", "ops/harvest.py", "ops/doctor.py",
             "ops/mac-bootstrap.sh", "ops/hive-cron.sh", "ops/mcp_server.py", "opencode.json")


def allowed(lane: str, task: str, path: str, prefix: str = PREFIX) -> bool:
    if not path.startswith(f"{prefix}/"):
        return False  # .github/ and anything outside the content folder: owner only
    inner = path[len(prefix) + 1:]
    if inner.startswith(PROTECTED):
        return False
    if lane == "jevx":
        return inner in GENERATED or inner == "ops/tasks.toml" or inner.startswith("ops/plan/")
    if inner.startswith("ops/done/"):
        return inner == f"ops/done/{task}.md"
    if inner in GENERATED or inner == "ops/tasks.toml":
        return False
    if lane == "hermes":
        return not inner.startswith(TOOLING)
    if lane == "opencode":
        return True
    return False


def check(branch: str, paths: list[str], prefix: str = PREFIX) -> list[str]:
    parts = branch.split("/")
    if len(parts) < 3 or parts[0] != "agent":
        return []
    lane, task = parts[1], parts[2]
    problems = [f"{lane} may not change {p}" for p in paths if not allowed(lane, task, p, prefix)]
    if lane in ("hermes", "opencode") and f"{prefix}/ops/done/{task}.md" not in paths:
        problems.append(f"missing receipt {prefix}/ops/done/{task}.md")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--branch", required=True)
    args = ap.parse_args(argv)
    paths = [line.strip() for line in sys.stdin if line.strip()]
    problems = check(args.branch, paths)
    for p in problems:
        print(f"ERROR {p}")
    print(f"{'FAIL' if problems else 'PASS'}: {args.branch}, {len(paths)} changed paths")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
